### ISSUE TITLE
LoadError: cannot load such file -- sassc

### ISSUE THREAD

**Issue by tfreedman** [rails/dartsass-rails#12]
I have an empty rails 7.0.2.2 app created just now that throws an error when using `rails assets:precompile`. 

```
$ rails assets:precompile
+ /home/me/.rvm/gems/ruby-3.1.0/gems/dartsass-rails-0.2.0/exe/linux/sass --load-path /home/me/sites/temp/temp/app/assets/stylesheets /home/me/sites/temp/temp/app/assets/stylesheets/application.scss:/home/me/sites/temp/temp/app/assets/builds/application.css
```

As far as I can tell, sprockets-rails provides the task `rails assets:precompile`, but isn't aware of dartsass, and is therefore complaining that there's no sass compiler. sassc-rails isn't in my Gemfile, which explains why sprockets is complaining, but adding it defeats the purpose of using dartsass-rails.

Is there some configuration option I'm missing, to presumably tell sprockets to stop handling sass in favor of dartsass-rails?

**Comment by dhh** [comment]
Good catch. I've fixed the installer in 19731626d2aff732521ad1965d604222cb30d1bc.

You need to add builds, remove stylesheets from the manifest. See the commit.
