### ISSUE TITLE
Hot reloading

### ISSUE THREAD

**Issue by brentgreeff** [rails/dartsass-rails#22]
What is the recommend approach to auto reloading? - if I save a scss file, I can see the automatic compilation to `app/assets/builds/application.css` - which is great, but it would be nice if the CSS was updated on the page I am viewing also. - Hot Module Replacement of some kind would be nice. - I guess I could watch the `app/assets/builds/` folder with the listen gem. - but it would be great if this was built in to this gem - or there were some tips in the readme

**Comment by dhh** [comment]
There’s currently nothing built specifically for that in this gem. Would be a general Rails feature to pursue.
