### ISSUE TITLE
does dartsass-rails support sprockets directives?

### ISSUE THREAD

**Issue by jwilsjustin** [rails/dartsass-rails#27]
Does dartsass-rails support [sprockets directives](https://github.com/rails/sprockets/blob/e36620745d7150fc33eccffeaf79e741a774499c/README.md#directives)? In my app, when dartsass builds, these directives are being treated as comments (which technically they are!) Just wondering if this is how it's supposed to work. Do we have to use `@import` or `@use` now?

```css
/* app/assets/dashboard.css */

/*
 *= require shared/base
 *= require_directory ./dashboard
 */
```

**Comment by rafaelfranca** [comment]
No. It doesn't. dartsaass-rails doesn't use sprockets to process the assets. It run a standalone dartsass process to do it.
