### ISSUE TITLE
FYI: dartsass-sprockets gem released (upgrade of sassc-rails gem)

### ISSUE THREAD

**Issue by johnnyshields** [rails/dartsass-rails#38]
I've released the following gems:

- [dartsass-sprockets](https://github.com/tablecheck/dartsass-sprockets), an upgrade of [sassc-rails](https://github.com/sass/sassc-rails)
- [dartsass-ruby](https://github.com/tablecheck/dartsass-ruby), an upgrade of [sassc-ruby](https://github.com/sass/sassc-ruby) which is mostly a compatibility shim for feature differences between SassC and Dart Sass. (This is planned to be removed.)

These gems use [sass-embedded](https://github.com/ntkme/sass-embedded-host-ruby/issues) under the hood, which provides Ruby native interface for Dart Sass.

The [SassC gem maintainers were unresponsive](https://github.com/sass/sassc-ruby/pull/240) so I went ahead and released a gem to benefit Sprockets users. The code is a bit of kludge at the moment. I'd be glad if Rails team wants to take these over, as the current dartsass-rails gem doesn't seem to gel as well (`dartsass:watch` and all is too much for a troglodyte developer like me to handle 🦖)

(cc: @xfalcox)

**Comment by januszm** [comment]
Does it mean this gem supports assets helpers such as the `image-url` ? Currently this is a bigger issue with dartsass-rails and requires adding a workaround such as this helper inside an initializer that is shared in many places on the Internet:

```ruby
class AssetUrlProcessor
  def self.call(input)
    context = input[:environment].context_class.new(input)
    data = input[:data].gsub(/(\w*)-url\...
```
