### ISSUE TITLE
 SassC::SyntaxError: Internal Error: Not enough space

### ISSUE THREAD

**Issue by KRSMHDK** [rails/dartsass-rails#44]
when running assets:precompile, I got SassC::SyntaxError: Internal Error: Not enough space

what's wrong?

running Ruby 3.2.0

**Comment by KRSMHDK** [comment]
From some reason when I used RAILS_ENV=development instead of RAILS_ENV=staging, it suddenly works

**Comment by wongyouth** [comment]
Same here, Cannot build on staging

**Comment by KRSMHDK** [comment]
> Same here, Cannot build on staging
I forgot how to fix this, but could you please try adding the following lines to application.rb?

    config.sass.preferred_syntax = :dartsass
    config.sass.syntax = :dartsass

**Comment by KRSMHDK** [comment]
or on staging.rb / production.rb

-  # config.assets.css_compressor = :sass
+  config.assets.css_compressor = nil

**Comment by wongyouth** [comment]
That works for me. 👍🏻

**Comment by yuanyuangu423** [comment]
> config.assets.css_compressor = nil
@KRSMHDK  Will there be any performance issues with this configuration without compression？
