### ISSUE TITLE
Built CSS is only picked up by second precompilation

### ISSUE THREAD

**Issue by steerio** [rails/dartsass-rails#48]
When one runs `rake assets:precompile`, the `dartsass:build` task is indeed run before the precompilation task, but it appears that the latter won't pick up assets written to the `app/assets/builds` folder by the former, *unless* the files had been present there before startup in the first place.

To reproduce the error:

1. Create a brand new Rails app, version 7.1.1.
2. Add dartsass-rails 0.5.0 to the Gemfile and bundle.
3. Run `rails dartsass:install`.
4. Put some styles in `app/assets/stylesheets/application.scss`.
5. Have at least one template or layout that does `stylesheet_link_tag "application"`.
6. Run `rake assets:precompile`.
7. Verify that there is an `app/assets/builds/application.css` file, so `dartsass:build` has run successfully.
8. Observe that neither is `application-<hash>.css` in the Sprockets manifest (`public/assets/.sprockets-manifest-*.json`), nor has it been packed up in `public/assets`.
9. Run `rake assets:precompile` again.
10. Observe that the task gave output corresponding to your SCSS file (and any additional assets that were referenced by it that are not referenced by other assets or your `manifest.js`), but nothing else.
11. Verify that `application-<hash>.css` is now in the Sprockets manifest and appears in `public/assets` as well.

Subsequent runs of `rake assets:precompile` will not yield any further changes (provided that none of the assets were modified).

**Comment by lbrito1** [comment]
I think I'm running into this too. Did you figure out a solution @steerio ?
https://discuss.rubyonrails.org/t/assets-precompile-skips-application-css-dartsass-rails/85133

**Comment by januszm** [comment]
This indeed is a problem, still in March 2024 after 4 months

**Comment by januszm** [comment]
@steerio  do you use `esbuild` ?
I noticed that this works correctly with webpack (`shakapacker`), problems started when I migrated to esbuild

**Comment by januszm** [comment]
Oh shoot, It's because of missing `app/assets/builds/.keep` indeed ! I just noticed this in my shakapacker=>esbuild migration branch
```
removed: app/assets/builds/.keep
```

**Comment by januszm** [comment]
Actually I would keep the issue and add a PR that resolves it, I think dartsass should create `app/assets/builds` if one does not exist.

**Comment by nimmolo** [comment]
Yes. I agree this seems necessary @janusm. It's a very inconvenient gotcha that actually brought our server down for hours yesterday, it took us awhile to figure what the heck could be wrong.

Tried a very minimal PR to switch a legacy Rails 7.1.3 app to `dartsass-rails` from `dartsass-sprockets` yesterday. Everything worked locally and in CI, but the deploy failed on production during `assets:precompile` with the above error. Even reverting the changes wouldn't allow the server to boot — at that point the `builds` folder _did_ exist, and threw off the `assets:precompile` process in a different way. Very frustrating and should not happen.

**Comment by nimmolo** [comment]
Is it possible that we just need to run this on production?
```
./bin/bundle add dartsass-rails
./bin/rails dartsass:install
```

**Comment by januszm** [comment]
I've just added this as an extra deployment step:

```sh
yarn install; bin/rails assets:precompile
```

if something is missing, it will do the work, if node_modules are installed and all assets precompiled already, it exits really fast so it won't delay the deployment.

**Comment by nimmolo** [comment]
thanks @januszm - Hm. Our deploy script already tries to run `assets:precompile` - that's where we're getting the failure.

**Comment by johnfisherman** [comment]
> I fixed this by adding back `app/assets/builds/.keep`, which I had deleted at some point.
> 
> I have this on my gitignore and dockerignore, which I believe is the default for Rails these days:
> 
> ```
> /app/assets/builds/*
> !/app/assets/builds/.keep
> ```

For some reason my .keep file was also lost somewhere in my development process. It took me 6 hours to figure this out, but hey, at least now I have an idea of how Sprocket and Dart Sass work together. Thanks for sharing, guys!
