### ISSUE TITLE
Imports doesn't work on production

### ISSUE THREAD

**Issue by mbajur** [rails/dartsass-rails#55]
Hello,

i have a pretty basic dartsass-rails setup in place. To simplify things - let's say i have an `application.scss` file with `@import 'notyf/notyf.min.css';` inside. While this `notyf` css file is being properly loaded in dev environment, after doing the release to production - it's not getting precompiled nor apparently even threat differently and precompiled `application.css` file still has a raw `@import 'notyf/notyf.min.css';` line which tries to load this file - it doesn't exist in `public` folder which means styles are not loaded. Notyf is an external dependency i have defined in my package.json file.

Am i missing something in here? Is that possible to import external dependencies in assets precomiled with dartsass-rails ? Shouldn't dartsass-rails inject imported external stylesheets on precompilation? My dartsass initializer is:

```
Rails.application.config.dartsass.builds = {
  "." => "."
}
```

Thanks in advance!

**Comment by shawnmaust** [comment]
I ran into something similar recently and learned that if there's a `.css` at the end of the import name, Sass will treat it as a plain CSS `@import` and not try to import it when compiling.

https://sass-lang.com/documentation/at-rules/import/#plain-css-imports
