### ISSUE TITLE
Error: Can't find stylesheet to import

### ISSUE THREAD

**Issue by sedubois** [rails/dartsass-rails#6]
Thanks a lot for this new gem which I'm trying to replace `sassc-rails` in our project (and some day we might manage to migrate away from sass entirely, who knows). 

We import some old foundation stylesheets like so: `@import "foundation/functions"`. With `sassc-rails` this correctly finds the file in the foundation gem under `vendor/assets/stylesheets/foundation/_functions.scss`, but when using `dartsass-rails` and running `rails dartsass:install` or `rails dartsass:build` it yields `Error: Can't find stylesheet to import`. The build error can be "solved" by copying the stylesheet from the gem into the app under `app/assets/stylesheets/foundation/_functions.scss`.

Should `vendor/assets/stylesheets` be added to `CSS_LOAD_PATH` in [`lib/tasks/build.rake`](https://github.com/rails/dartsass-rails/blob/a6fd2838bf01a7706e61419f381036c711e0bf24/lib/tasks/build.rake#L2)?

**Comment by dhh** [comment]
Yes, would be good to add that. And have it possible of configuring it.

**Comment by sedubois** [comment]
Currently the stylesheets are assumed to be under `Rails.root` (`Rails.root.join("app/assets/stylesheets")`). How to search stylesheets in the gems as well?

**Comment by chipairon** [comment]
@dhh I made a PR that should address this concern https://github.com/rails/dartsass-rails/pull/7
For @sedubois case I belive that something similar to this might work (assuming you are referring to [this gem](https://github.com/foundation/foundation-rails)):
```ruby
# config/initializers/dartsass.rb
Rails.application.config.dartsass.extra_load_paths = [
  "#{`bundle show foundation-rails`.strip}/vendor/assets/scss"
]
```

**Comment by chipairon** [comment]
With https://github.com/rails/dartsass-rails/pull/11 it won't need any extra configuration.

**Comment by mockdeep** [comment]
We're still seeing this issue on version 0.3.0 with [`font-awesome-rails`](https://github.com/bokmann/font-awesome-rails).

```
Error: Can't find stylesheet to import.
   ╷
21 │ @import 'font-awesome';
```

**Comment by chipairon** [comment]
@mockdeep It is because [the file](https://github.com/bokmann/font-awesome-rails/tree/master/app/assets/stylesheets) doesn't have a conventional naming that [Sass expects](https://sass-lang.com/documentation/at-rules/import#finding-the-file) (it ends with .css.erb)
It seems to work if the import is `@import 'font-awesome.css';`
[Here](https://github.com/chipairon/dartsass-demo/commit/9e43af3d047a1f02564069dad5a50658f38b3a9f#diff-0869e3045a3b5ca0e44ed193977d1568d686ca2373f4b93a8a868e4099fc932dR1) is a demo app with it working.

**Comment by mockdeep** [comment]
Thanks @chipairon. Now to fix the thousand other things that don't seem to be working for us on Dart Sass.
