### ISSUE TITLE
installs in JRuby and it looks like it shouldn't

### ISSUE THREAD

**Issue by rebelwarrior** [rails/dartsass-rails#8]
It installs on JRuby but when you run the `bin/rails dartsass:install`  command it fails 

```
[...]
Compile initial Dart Sass build
         run  rails dartsass:build from "."
ERROR: dartsass-rails does not support the java operating system

```

**Comment by dhh** [comment]
Where else would we detect this?

**Comment by JesseChavez** [comment]
Hi, I see a similar issue when I try  to use this gem with JRuby.

when I run:
```
bundle exec rails dartsass:watch --trace
```
I get the below error:
```
** Execute dartsass:watch
ERROR: dartsass-rails does not support the universal-java platform
```

It seems JRuby behave slightly different compared to Ruby

In JRuby we get the following:
```
[9] pry(main)> platform_info = Gem::Platform.local
=> #<Gem::Platform:0x7f12094d @os="java", @version="11", @cpu="universal" @cpu="universal", @os="java", @version="11">
[10] pry(main)> platform_string = "#{platform_info.cpu}-#{platform_info.os}"
=> "universal-java"
```

**Comment by JesseChavez** [comment]
Hi @dhh,

After digging a bit in the code I reckon I fixed this issue, I submitted a PR https://github.com/rails/dartsass-rails/pull/16
